/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Animation.rig (K: BlackHorn) (https://sketchfab.com/black.horn_860)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/imac-g3-upgraded-6b5974d30eb640d294f86c9ad43443e4
Title: Imac G3 - Upgraded
*/

import * as THREE from 'three'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import MacScene from '../assets/3D/imac.glb'
import { Canvas, useFrame } from '@react-three/fiber'
import PostProcessingEffects from '../components/Effects'
import { Suspense, useRef } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
  }
}

const IMac = (props: JSX.IntrinsicElements['group']) => {

  const { nodes } = useGLTF(MacScene) as GLTFResult

  const material = new THREE.MeshStandardMaterial({ color: 0x00ff00, opacity: 0.85, transparent: true })

  const meshRef = useRef<THREE.Mesh>(null!)

  useFrame((_, delta) => (meshRef.current.rotation.y += delta))

  return (
    <group ref={meshRef} {...props} dispose={null}>
      <group position={[-0.454, 0, 0.335]} rotation={[-Math.PI / 2, 0, 0]} scale={0.039}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={material}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={material}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={material}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={material}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={material}
            position={[6.908, 8.39, -8.668]}
            scale={1.01}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MacScene)

export default () => (
    <Canvas
        orthographic
        // shadows
        camera={{
        position: [0, 0, 500],
        }}
    >
        <OrbitControls
        enableZoom={false}
        minPolarAngle={Math.PI / 2}
        maxPolarAngle={Math.PI / 2}
        />
        <ambientLight intensity={0.5} />
        <directionalLight position={[0, 0, 10]} intensity={0.9} />
        <directionalLight position={[0, 0, -10]} intensity={0.9} />
        <PostProcessingEffects />
        <Suspense fallback={null}>
            <mesh scale={110} position={[0, -20, 0]}>
                <IMac />
            </mesh>
        </Suspense>
    </Canvas>
  );
