/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: David SV (https://sketchfab.com/davidsvj)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-monitor-f85da850be324b308bb3206ff5e86d3f
Title: Retro Computer Monitor
*/

import * as THREE from 'three'
import { Loader, OrbitControls, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import MonitorCRTScene from '../assets/3D/retro_computer_monitor.glb'
import { Canvas, useFrame } from '@react-three/fiber'
import PostProcessingEffects from '../components/Effects'
import { Suspense, useRef } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
  }
}

const MonitorCRT = (props: JSX.IntrinsicElements['group']) => {
  const { nodes } = useGLTF(MonitorCRTScene) as GLTFResult

  const meshRef = useRef<THREE.Mesh>(null!)

  useFrame((_, delta) => (meshRef.current.rotation.y -= delta))

  return (
    <group ref={meshRef} {...props} dispose={null}>
      <group scale={[1.905, 2.198, 2.393]}>
        <mesh geometry={nodes.Object_4.geometry} material={new THREE.MeshStandardMaterial({ color: 0x00ff00, opacity: 0.85, transparent: true })} />
        <mesh geometry={nodes.Object_5.geometry} material={new THREE.MeshStandardMaterial({ color: 0x00ff00, opacity: 0.85, transparent: true })} />
      </group>
    </group>
  )
}

useGLTF.preload(MonitorCRTScene)

export default () => (
    <Canvas
        orthographic
        // shadows
        camera={{
        // zoom: -20,
        position: [0, 0, 100],
        }}
    >
        <OrbitControls
        enableZoom={false}
        minPolarAngle={Math.PI / 2}
        maxPolarAngle={Math.PI / 2}
        />
        <ambientLight intensity={0.5} />
        <directionalLight position={[0, 0, 10]} intensity={0.9} />
        <directionalLight position={[0, 0, -10]} intensity={0.9} />
        <PostProcessingEffects />
        <Suspense fallback={<Loader />}>
        <mesh scale={15} position={[0, 0, 0]}>
            <MonitorCRT />
        </mesh>
        </Suspense>
    </Canvas>
  );