/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import PaletteScene from '../assets/3D/palette.glb'
import { Canvas } from '@react-three/fiber'
import PostProcessingEffects from '../components/Effects'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
    nodes: {
      defaultMaterial003: THREE.Mesh
    }
  }

const Palette = (props: JSX.IntrinsicElements['group']) => {

  const { nodes } = useGLTF(PaletteScene) as GLTFResult

  const material = new THREE.MeshStandardMaterial({ color: 0x00ff00, opacity: 0.85, transparent: true })

  const meshRef = useRef<THREE.Mesh>(null!)

  useFrame((_, delta) => (meshRef.current.rotation.y += delta))

  return (
    <group ref={meshRef} {...props} dispose={null}>
      <group position={[4.373, -0.631, -0.279]} rotation={[-1.219, -0.019, -0.043]} scale={0.125}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.defaultMaterial003.geometry}
              material={material}
              position={[-0.171, 0.031, 0.173]}
              rotation={[-0.722, -0.173, 0.019]}
              scale={0.444}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(PaletteScene)

export default () => (
    <Canvas
        orthographic
        // shadows
        camera={{
            position: [0, 0, 100],
            // rotation: [0, -Math.PI / 2, -Math.PI / 2],
        }}
    >
        <OrbitControls
        enableZoom={false}
        minPolarAngle={Math.PI / 2}
        maxPolarAngle={Math.PI / 2}
        />
        <ambientLight intensity={0.5} />
        <directionalLight position={[0, 0, 10]} intensity={0.9} />
        <directionalLight position={[0, 0, -10]} intensity={0.9} />
        <PostProcessingEffects />
        <Suspense fallback={null}>
            <mesh scale={6}>
                <Palette />
            </mesh>
        </Suspense>
    </Canvas>
  );
