/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: stevespencer (https://sketchfab.com/stevespencer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-940ec24a2e4f4807ae862dfa6d7f6af9
Title: UFO
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import UfoScene from '../assets/3D/ufo.glb'

export function UfoModel(props) {
  const { nodes, materials } = useGLTF(UfoScene)
  return (
    <group {...props}>
      <group scale={[4.348, 1, 4.348]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Engine_Blue}
        />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Body} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Dome}
        position={[0, 0.24, 0]}
        scale={2.406}
      />
    </group>
  )
}

useGLTF.preload(UfoScene)